language: python
python:
- '2.7'
script:
- echo pypi deployment
deploy:
  - provider: pypi
    user: longma
    password:
      secure: lbgsMlfYnRJ/S/Vkk+J607achlxgd35tfdvRKQ8XEP4RlmVCv+3OpoUIFLX8k7VeUDpeyYArTaTGP1OQuuXq0tue6Skt9ozzz0t7xgiG4hidCYXNeH1dO53/e1L/agYF4ov7vnElXrtayvgHkhJM/gDQSFe91GB71sGK4DGpcImpcc6FVlXKk7iSUqtBCLYxi0ngPTJWewyO3ASMGL5w7hZvEu0SvzgOB2JWMtUMO8Q0bsLtGL7GYaJmRL/U7/UVfdJmq4slFcASwePMT2/GzUqcpdgPFWy/Cg7xjJiS3TSNXSbT3ykp+G7qUEtTnMIaSUXaQOkQ3j626aUPTcLdWk8+Pf8Zo7FsVDl/pGyATz/Kf6ELa4MMKLZtr3WaH7WwNs2zILGlgS4WIHwpiSVsshXd8fLiIdje72FdVpqSETYtcOVIvODUcKcj
    distributions: sdist bdist_wheel
  - provider: pypi
    user: longma
    password:
      secure: lbgsMlfYnRJ/S/Vkk+J607achlxgd35tfdvRKQ8XEP4RlmVCv+3OpoUIFLX8k7VeUDpeyYArTaTGP1OQuuXq0tue6Skt9ozzz0t7xgiG4hidCYXNeH1dO53/e1L/agYF4ov7vnElXrtayvgHkhJM/gDQSFe91GB71sGK4DGpcImpcc6FVlXKk7iSUqtBCLYxi0ngPTJWewyO3ASMGL5w7hZvEu0SvzgOB2JWMtUMO8Q0bsLtGL7GYaJmRL/U7/UVfdJmq4slFcASwePMT2/GzUqcpdgPFWy/Cg7xjJiS3TSNXSbT3ykp+G7qUEtTnMIaSUXaQOkQ3j626aUPTcLdWk8+Pf8Zo7FsVDl/pGyATz/Kf6ELa4MMKLZtr3WaH7WwNs2zILGlgS4WIHwpiSVsshXd8fLiIdje72FdVpqSETYtcOVIvODUcKcj
    distributions: sdist bdist_wheel
    on:
      tags: true
after_deploy:
- echo DONE
