language: python
python:
- '2.7'
script:
- echo pypi deployment
deploy:
  - provider: pypi
    user: longma
    password:
      secure: bcag8ICAKkl0KJ/ECU0suMxWsk834UL4Nz5jYxb03D6l6MlauPrB5K7k/VSzHxHU7ApIlme6XDGMIJ6Ykg99tjLpFm1UxS7LCSapEj9xWRH+7W3yLrelWxVIicBkjPTpcfmDw6MbYEj5Grx+VXUJlAQpR5Ft21Z9/ZuFmMs69K5iCnknqgaVThR8iwaPeqTM/pdX+WsBzdwVTGk/bQ9Suuv9ky9DjRMAGPQMC6HleC+a3PNXwWd3qdy5y4qrAdIa/LRSU/rrWAYnobcgfOEj/aVooVx+cx+8fs9ZXiwNw1KT7TsY+xdHPD6H45wj2Al+4PGW75x94t3uixmS5QqPHoi4u2uZk5LV57rd6o0PvDVNGKKTdJQ5wFnr3BoG2Z1VPVC5URPGUOGsIAY9iw7rvtVwbBgSLve/2hl/+YysbkxIl7v7MGPUIy9JF/nK6j1FeCCGC6fK2e2C/lH+wKVTz4IBM/b8D3qCId8KWQq3HBMEdxT26m+iPaJYa3GyvZShBzGgQ4hCK4jcgJ2o2Vu+yjCjL6gkNIsJZnXZ/0ABJMFAvOf+vSrivP/nGSaIZVuEHAjJlCd6KwjenSjW+wy5AhLUHOegGcmHMBomHM64Q6PO1NLbuInWT/JHXQiXf1dcj2La4fR7XQ1ISzWegjGu7vQ2PVFnCDZFrh5IEEslQ58=
    distributions: sdist bdist_wheel
  - provider: pypi
    user: longma
    password:
      secure: bcag8ICAKkl0KJ/ECU0suMxWsk834UL4Nz5jYxb03D6l6MlauPrB5K7k/VSzHxHU7ApIlme6XDGMIJ6Ykg99tjLpFm1UxS7LCSapEj9xWRH+7W3yLrelWxVIicBkjPTpcfmDw6MbYEj5Grx+VXUJlAQpR5Ft21Z9/ZuFmMs69K5iCnknqgaVThR8iwaPeqTM/pdX+WsBzdwVTGk/bQ9Suuv9ky9DjRMAGPQMC6HleC+a3PNXwWd3qdy5y4qrAdIa/LRSU/rrWAYnobcgfOEj/aVooVx+cx+8fs9ZXiwNw1KT7TsY+xdHPD6H45wj2Al+4PGW75x94t3uixmS5QqPHoi4u2uZk5LV57rd6o0PvDVNGKKTdJQ5wFnr3BoG2Z1VPVC5URPGUOGsIAY9iw7rvtVwbBgSLve/2hl/+YysbkxIl7v7MGPUIy9JF/nK6j1FeCCGC6fK2e2C/lH+wKVTz4IBM/b8D3qCId8KWQq3HBMEdxT26m+iPaJYa3GyvZShBzGgQ4hCK4jcgJ2o2Vu+yjCjL6gkNIsJZnXZ/0ABJMFAvOf+vSrivP/nGSaIZVuEHAjJlCd6KwjenSjW+wy5AhLUHOegGcmHMBomHM64Q6PO1NLbuInWT/JHXQiXf1dcj2La4fR7XQ1ISzWegjGu7vQ2PVFnCDZFrh5IEEslQ58=
    distributions: sdist bdist_wheel
    on:
      tags: true
after_deploy:
- echo DONE
