language: python
python:
- '2.7'
script:
- echo pypi deployment
deploy:
  - provider: pypi
    user: lucyking
    password:
      secure: PivMPu+MdNRg/WYheQIX98EfGQlxV1R8lWxR9OGeEwRcBeuui3YYXcvQIzZgp/LCrZlOPPfzkkiVac8Ozz705Tw7OWqRXwszLPIL6eu1ljTw3ebjrUwbjaRLAx6kPdY09BDzNKOMANOFnQDyqCK56B3YIJZGoe+Uum0hkATRxoiIOLeSWSrkfwGYRpnXDZdczW/4kL70O4qW6+U6iurOV8xiEL2rcrNrQcYALLUMuwVRLhOIG+SoR7aUdpTgeW4AokIDZLjQSc3Xza2FIVWHXemA5xOXJ5BX7VWxUjvyZR6yg0dw4oXTaLXOBxNjZRZmvKp2b7jeJEe2Db6Xgv2I7CyNK3nUghGGemMepG9zhPlVFuPAl9JNEDCnNeGkKRZDGAt86T1ONVCSyZoQjW4AyQ9sInYMD90KUMdIBNZiqUXs42fqcTeaUowmgpR/fZh3/oPBpsqHOKDr/8qTIVVFiQpy5Fn1yJbOQ8WmdWvIiiXau1C2r1aseFVT/W879bPaFvXlhobrVNfb07l2PaL4tuZNumCjSnJqG6B0amdPIcaJ+tP4gm6stXStactqh2sjNtVssla+e6xNK2fFvl0IkI8EVrEeVA55lFjwLye5VA4Qc2hhiYOMwcrzScG9G4F7BfgPFm6yYKLdBwqDknhnQNaBiIM0rP0deZY6YXqq/bY= 
    distributions: sdist bdist_wheel
  - provider: pypi
    user: lucyking
    password:
      secure: PivMPu+MdNRg/WYheQIX98EfGQlxV1R8lWxR9OGeEwRcBeuui3YYXcvQIzZgp/LCrZlOPPfzkkiVac8Ozz705Tw7OWqRXwszLPIL6eu1ljTw3ebjrUwbjaRLAx6kPdY09BDzNKOMANOFnQDyqCK56B3YIJZGoe+Uum0hkATRxoiIOLeSWSrkfwGYRpnXDZdczW/4kL70O4qW6+U6iurOV8xiEL2rcrNrQcYALLUMuwVRLhOIG+SoR7aUdpTgeW4AokIDZLjQSc3Xza2FIVWHXemA5xOXJ5BX7VWxUjvyZR6yg0dw4oXTaLXOBxNjZRZmvKp2b7jeJEe2Db6Xgv2I7CyNK3nUghGGemMepG9zhPlVFuPAl9JNEDCnNeGkKRZDGAt86T1ONVCSyZoQjW4AyQ9sInYMD90KUMdIBNZiqUXs42fqcTeaUowmgpR/fZh3/oPBpsqHOKDr/8qTIVVFiQpy5Fn1yJbOQ8WmdWvIiiXau1C2r1aseFVT/W879bPaFvXlhobrVNfb07l2PaL4tuZNumCjSnJqG6B0amdPIcaJ+tP4gm6stXStactqh2sjNtVssla+e6xNK2fFvl0IkI8EVrEeVA55lFjwLye5VA4Qc2hhiYOMwcrzScG9G4F7BfgPFm6yYKLdBwqDknhnQNaBiIM0rP0deZY6YXqq/bY= 
    distributions: sdist bdist_wheel
    on:
      tags: true
after_deploy:
- echo DONE
